"""
Code generation utilities for differentiable programs.

Converts discretized PrimitiveGraphs into complete, executable Python
programs that SkyDiscover's evaluator can run.
"""

from __future__ import annotations

import logging
from typing import Optional

from skydiscover.search.differentiable.discretizer import discretize_graph

logger = logging.getLogger(__name__)


def graph_to_solution(graph, function_name: str = "algorithm", docstring: Optional[str] = None) -> str:
    """Generate a complete Python solution from a PrimitiveGraph.

    Produces a standalone function with proper imports and structure
    that can be written to a file and evaluated by SkyDiscover's evaluator.

    Args:
        graph: The PrimitiveGraph to convert.
        function_name: Name for the generated function.
        docstring: Optional docstring to include.

    Returns:
        Complete Python source code string.
    """
    # Get the discretized algorithm code
    algo_code = discretize_graph(graph)

    # Build complete solution
    lines = []
    lines.append('"""Auto-generated by differentiable search."""')
    lines.append("")

    if docstring:
        lines.append(f'# {docstring}')
        lines.append("")

    lines.append(algo_code)
    lines.append("")

    return "\n".join(lines)


def wrap_with_evolve_block(code: str, block_name: str = "algorithm") -> str:
    """Wrap generated code in EVOLVE-BLOCK markers.

    SkyDiscover uses these markers to identify mutable regions
    in the source code.

    Args:
        code: The code to wrap.
        block_name: Name for the evolve block.

    Returns:
        Code wrapped in EVOLVE-BLOCK markers.
    """
    return f"# EVOLVE-BLOCK-START {block_name}\n{code}\n# EVOLVE-BLOCK-END {block_name}\n"
