"""
Evaluator for sorting algorithms generated by gradient-based search.

Tests the generated `algorithm` function on random arrays of varying sizes
and returns a combined_score representing the fraction of correctly sorted outputs.
"""

import random


def evaluate(program_path):
    """Evaluate a sorting algorithm.

    Expects the program to define an `algorithm(*elements)` function
    that takes N numeric arguments and returns them sorted ascending.

    Args:
        program_path: Path to the generated Python file.

    Returns:
        Dict with combined_score (0.0 to 1.0).
    """
    with open(program_path) as f:
        code = f.read()

    namespace = {}
    try:
        exec(code, namespace)
    except Exception as e:
        return {"combined_score": 0.0, "error": f"exec failed: {e}"}

    algorithm = namespace.get("algorithm")
    if algorithm is None:
        return {"combined_score": 0.0, "error": "No 'algorithm' function found"}

    correct = 0
    total = 100
    errors = 0

    for _ in range(total):
        n = random.randint(2, 5)
        arr = [random.uniform(-10, 10) for _ in range(n)]
        try:
            result = algorithm(*arr)
            if isinstance(result, tuple):
                result = list(result)
            elif not isinstance(result, list):
                result = [result]
            expected = sorted(arr)
            # Check approximate equality (floats)
            if len(result) == len(expected) and all(
                abs(r - e) < 1e-6 for r, e in zip(result, expected)
            ):
                correct += 1
        except Exception:
            errors += 1

    score = correct / total
    return {
        "combined_score": score,
        "correct": correct,
        "total": total,
        "errors": errors,
    }
